<?php
use App\Models\Tarif;
use Illuminate\Database\Seeder;

class TariffsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       
            $tarif=new Tarif();
            $tarif->kg = '0.5';
            $tarif->price = '8.09';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '1';
            $tarif->price = '8.09';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '1.5';
            $tarif->price = '9.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '2';
            $tarif->price = '9.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '2.5';
            $tarif->price = '9.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '3';
            $tarif->price = '9.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '3.5';
            $tarif->price = '9.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '4';
            $tarif->price = '9.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '4.5';
            $tarif->price = '9.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '5';
            $tarif->price = '9.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '5.5';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '6';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '6.5';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '7';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '7.5';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '8';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '8.5';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '9';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '9.5';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '10';
            $tarif->price = '10.57';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '11';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '12';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '13';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '14';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '15';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '16';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '17';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '18';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '19';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '20';
            $tarif->price = '12.74';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '21';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '22';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '23';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '24';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '25';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '26';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '27';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '28';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '29';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '30';
            $tarif->price = '16.21';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '40';
            $tarif->price = '23.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '50';
            $tarif->price = '23.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '60';
            $tarif->price = '29.54';
            $tarif->company_id = '1';
            $tarif->save();
            $tarif=new Tarif();
            $tarif->kg = '70';
            $tarif->price = '35.54';
            $tarif->company_id = '1';
            $tarif->save();
        
    }
}
